apiVersion: v1
data:
  access-log-params: "buffer=320k flush=5m"
  keep-alive-requests: "1000000"
  max-worker-connections: "100000"
  max-worker-open-files: "100000"
  use-proxy-protocol: "true"
  lua-shared-dicts: 'configuration_data: 200'
  # max-worker-open-files: "100000"
kind: ConfigMap
metadata:
  name: nginx-ingress-ingress-nginx-controller
