apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer # not namespaced, https://docs.cert-manager.io/en/release-0.11/reference/clusterissuers.html
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: info@openode.io
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class:  nginx