apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: ns-kuard1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: cinder-classic