---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginxtest
  namespace: instance-152
spec:
  tls:
    - secretName: mysecret
      hosts:
        - example.com
  rules:
    - host: example.com
      http:
        paths:
          - backend:
              serviceName: nginx
              servicePort: 80
